version: '3.8'
services:
  bridge:
    build:
      context: "../nodejs"
      dockerfile: "../docker/Dockerfile"
    command: node build/src/apps/bridge.js
    restart: always
    environment:
      - BOOT_MODE
      - KEY_TO_BOOT
      - TARGET_URL=http://canary:3000
      - TARGET_METHOD
      - SENTRY_DSN
      - BOOT_CONFIG_FILE_PATH
      - CACHE_URL=http://cache:3001
      - CACHE_PORT
    depends_on:
      - cache
  cache:
    build:
      context: "../nodejs"
      dockerfile: "../docker/Dockerfile"
    command: node build/cache.js
    restart: always
    ports:
      - '3001:3001'
    environment:
      - BOOT_MODE
      - KEY_TO_BOOT
      - TARGET_URL=http://target:3000
      - TARGET_METHOD
      - SENTRY_DSN
      - BOOT_CONFIG_FILE_PATH
      - CACHE_URL=http://cache:3001
      - CACHE_PORT=3001
    volumes:
      - type: bind
        source: ../shell/boot.json
        target: /app/shell/boot.json
  target:
    build:
      context: "../nodejs"
      dockerfile: "../docker/Dockerfile"
    command: node build/target.js
    restart: always
    ports:
      - '3000:3000'
    environment:
      - BOOT_MODE
      - KEY_TO_BOOT
      - TARGET_URL=http://target:3000
      - TARGET_METHOD
      - SENTRY_DSN
      - BOOT_CONFIG_FILE_PATH
      - CACHE_URL=http://cache:3001
      - CACHE_PORT=3001
