name: Analyze

on:
  pull_request:
    types: []

env:
  _XMTPB_API_URL: ${{ vars.ANALYZE_XMTPB_API_URL }}
  _XMTPB_API_PORT: ${{ vars.ANALYZE_XMTPB_API_PORT }}
  _XMTPB_WEBHOOK_KEY: ${{ secrets.ANALYZE_XMTPB_WEBHOOK_KEY }}
  _XMTPB_PG_CONNECTION_STRING: ${{ secrets.ANALYZE_XMTPB_PG_CONNECTION_STRING }}
  _XMTPB_POSTGRES_USER: ${{ secrets.ANALYZE_XMTPB_POSTGRES_USER }}
  _XMTPB_POSTGRES_PASSWORD: ${{ secrets.ANALYZE_XMTPB_POSTGRES_PASSWORD }}
  _XMTPB_SIGNUP_KEY: ${{ secrets.ANALYZE_XMTPB_SIGNUP_KEY }}
  _XMTPB_IMAGE_TAG: ${{ vars.ANALYZE_XMTPB_IMAGE_TAG }}

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: eslint
        run: |
          cd nodejs
          npm i
          npm run static:eslint
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: prettier
        run: |
          cd nodejs
          npm i
          npm run static:prettier
  tsc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: tsc
        run: |
          cd nodejs
          npm i
          npm run static:tsc
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: tsc
        run: |
          cd nodejs
          npm i
          npm run static:tsc
      - name: smoke tests
        run: |
          cd nodejs
          npm run docker:api:up
          npm run docker:api:test
          npm run docker:bridge:up
          npm run docker:bridge:test

      
